workspace: "examples"
num_theorems: 3

petanque:
  address: 127.0.0.1
  port: 8765
  timeout: 10
  run_opts: null
  context: true

agent:
  model_id: gpt-4o
  temperature: 1.0

search:
  kind: template
  mode: naive
  max_steps: 10

defaults:
  - _self_
  - benchmark: example
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none


